name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        working-directory: MarkdownEditor
        run: |
          xcodebuild test \
            -project MarkdownEditor.xcodeproj \
            -scheme MarkdownEditor \
            -destination 'platform=macOS'
